syuilo/misskey

src/api/endpoints/users/posts.js
It will be available at username as well.
=> Improve convenience.

.gitignore, src/api/endpoints/meta.js
- Add package 'nodegit'
- Fix path to repository
=> [API]Fix /meta

src/web/app/mobile/tags/ui-nav.tag
~ローカルでテスト環境建ててないので確認できてないけどたぶんいいとおもう~
テスト環境建ててフラットデザインにした
=> [Mobile] ui-nav: match colour w/ new theme

src/web/app/mobile/tags/ui-nav.tag
=> Remove href attribute.

src/web/app/desktop/tags/settings-window.tag, src/web/app/desktop/tags/settings.tag
flexbox使ってるけどホームとかに`position:sticky;`あるから問題ない(^^♪
=> 設定画面の見栄えをましにする

src/web/app/mobile/tags/ui-nav.tag
=> Add MisskeyTV link.

src/web/app/common/tags/public-timeline.tag
close #217.
タイムラインと同等の処理をされた投稿を表示する為の改修です。
=> show processed posts at public timeline on entrance

package.json, src/common/text/elements/emoji.js, src/common/text/index.js, src/web/app/common/scripts/text-compiler.js, test/text.ts
escapeしてないのは正規表現で引っかからないだろってのがあるからですが、もし仮に必要ならそれコミットします
https://file.himasaku.net/58b5e2679ef5975a2087b08d/untitled.png
#21 関連で、`wontfix`でクローズされてますが再考を
=> support emoji

.travis.yml, .travis/after_success.sh
Exit immediately after testing if releasing task is not needed
=> Extract after_success

src/web/app/desktop/tags/home-widgets/profile.tag
This PR makes it easy to understand that the dialog is shown on clicking.
=> Enhance profile widget

src/web/app/desktop/tags/settings.tag
Fix https://misskey.xyz/Citrine/58db870c52f7075ea20cb2a6
=> Enhance birthday textbox

src/web/app/desktop/tags/home-widgets/recommended-polls.tag
=> #338 Add link to individual page.

package.json
Closes #405
https://greenkeeper.io/
=> fix(package): update accesses to version 2.5.0

package.json
=> fix(package): update debug to version 2.6.5

package.json
Closes #440
https://greenkeeper.io/
=> chore(package): update @types/mongodb to version 2.2.2

package.json
=> fix(package): update reconnecting-websocket to version 3.0.5

locales/ja.yml, src/web/app/desktop/tags/user-profile.tag, src/web/app/mobile/tags/user.tag
=> デスクトップ、モバイル共に投稿数の表示

package.json, src/web/app/common/scripts/text-compiler.js
今度は小さいサイズになるようにgemojiを圧縮しているモジュールを使っている為ファイルサイズ増加は727 KB -> 749 KB (+ 22 KB) です
resolve #21
=> emoji描画の再サポート

package.json
=> fix(package): update pictograph to version 2.0.4

package.json
=> Revert "Update ts-node to the latest version 🚀"

package.json
=> Revert "Update @types/gulp to the latest version 🚀"

package.json
=> fix(package): update elasticsearch to version 13.2.0

package.json
=> chore(package): update @types/node to version 8.0.2

package.json
=> chore(package): update uglify-es to version 3.0.24

package.json
=> chore(package): update @types/request to version 2.0.0

package.json
=> chore(package): update @types/node to version 8.0.14

package.json
=> chore(package): update @types/node to version 8.0.17

package.json
=> fix(package): update ts-node to version 3.3.0

package.json
=> chore(package): update @types/webpack to version 3.0.7

package.json
=> fix(package): update elasticsearch to version 13.3.1

package.json
=> fix(package): update crypto to version 1.0.1

package.json
=> fix(package): update reconnecting-websocket to version 3.1.1

package.json
=> chore(package): update @types/node to version 8.0.24

package.json
=> fix(package): update cropperjs to version 1.1.1

package.json, src/api/common/add-file-to-drive.ts, src/api/endpoints/drive.ts, src/api/endpoints/drive/files.ts, src/api/endpoints/drive/files/find.ts, src/api/endpoints/drive/files/show.ts, src/api/endpoints/drive/files/update.ts, src/api/endpoints/drive/folders/find.ts, src/api/endpoints/drive/folders/update.ts, src/api/endpoints/messaging/messages/create.ts, src/api/endpoints/posts/create.ts, src/api/endpoints/posts/timeline.ts, src/api/models/drive-file.ts, src/api/serializers/drive-file.ts, src/api/serializers/drive-folder.ts, src/api/serializers/post.ts, src/api/serializers/user.ts, src/db/mongodb.ts, src/file/server.ts, test/api.js, tools/migration/use-gridfs.js
* post
* user
*  /posts/timeline
=> improve performance & use GridFS for files

package.json
=> fix(package): update file-type to version 7.2.0

package.json
=> chore(package): update @types/request to version 2.0.7

package.json
=> chore(package): update @types/mongodb to version 2.2.15

package.json
=> chore(package): update @types/morgan to version 1.7.35

package.json
=> chore(package): update @types/elasticsearch to version 5.0.17

package.json
=> chore(package): update @types/gulp-uglify to version 3.0.3

package.json
=> chore(package): update uglify-es to version 3.1.8

package.json, tools/migration/change-gridfs-metadata-name-to-filename.js, tools/migration/issue_882.js, tools/migration/use-gridfs.js
すべて第一引数で 並列数 を指定できます (デフォルト値は `5`)
=> マイグレーションを並列で走らせる

src/file/server.ts
メモリ利用量が改善します (逐次chunkが発行されそのままバイパスされ書き込まれるため)
=> file - use readableStream

package.json
=> chore(package): update @types/node to version 8.0.53

package.json
=> fix(package): update @types/node to version 8.0.57

package.json
=> fix(package): update @types/chai to version 4.0.8

package.json
=> fix(package): update pictograph to version 2.1.5

src/web/app/desktop/tags/images-viewer.tag, src/web/app/desktop/tags/post-detail-sub.tag, src/web/app/desktop/tags/post-detail.tag, src/web/app/desktop/tags/timeline.tag
=> Display image better #981

package.json
=> fix(package): update @types/chai to version 4.0.10

package.json
=> fix(package): update cropperjs to version 1.2.1

package.json
=> fix(package): update ts-node to version 4.1.0

package.json
=> fix(package): update qrcode to version 1.2.0

src/config.ts, src/server.ts
This is missing part of commit 0109e0811c4142153ae3f915295e62630653909e.
=> Define hostname and secondary_hostname in config

src/web/app/mobile/views/pages/user.vue
=> モバイル版のユーザーページの表示切り変えnavを上についてくるように

package.json
=> fix(package): update element-ui to version 2.3.2

package.json
=> fix(package): update bootstrap-vue to version 2.0.0-rc.4

package.json
=> fix(package): update bootstrap-vue to version 2.0.0-rc.6

src/processor/http/perform-activitypub.ts, src/processor/http/process-inbox.ts, src/remote/activitypub/act/index.ts, src/remote/activitypub/create.ts, src/remote/activitypub/resolver.ts
The value of the value returned by resolveRemoteUserObjects method of
remote/activitypub/resolver was inconsistent.
=> Remove resolveRemoteUserObjects method of remote/activitypub/resolver

src/client/app/common/views/components/signup.vue, src/client/app/dev/views/new-app.vue, src/models/app.ts, src/models/user.ts, src/text/parse/elements/mention.ts, test/text.ts
* Allow underscore instead of hypen
* Fix domain part handling
* Add tests for remote mention
=> Fix username/mention regexes

package.json
=> fix(package): update @types/node to version 9.6.4

src/server/file/index.ts
Closing #1439 and #1440
ImageMagickがライブラリを持っている範囲で処理するようにした
動画のサムネイルの生成の準備工事も行った
=> Provide thumb for more types

DONATORS.md, README.md
自分はネイティブスピーカーではないですが`donors`でも意味は通じますが基本的に寄付などの意味では`donators`のほうが良く使われているのでこちらのほうが良いかと思います。
あとは少し気になった部分を変更しました。
=> Use more natural words

docs/setup.en.md
=> Add node-gyp instructions to build the crypto module

locales/fr.yml
Here is the french translation! Thanks again for that awesome SNS you guys are building!
=> added french(fr.yml)

docs/translate.en.md
=> fixed translate.en.md

docs/translate.en.md
#1491 introduced some errors in translate.en.md.
This reverts some of its changes and tries to improve the original translation.
=> Fix translate.en.md

package.json
=> fix(package): update @types/mongodb to version 3.0.15

locales/index.ts, locales/pl.yml, src/client/app/desktop/views/components/settings.vue
=> i18n: Add Polish translation

src/client/docs/api/gulpfile.ts, src/client/docs/gulpfile.ts
https://misskey.xyz/notes/5afd405712a8cf0184ed6c83 の件
=> Fix can't convert i18n docs

locales/ja.yml, src/client/app/common/views/components/visibility-chooser.vue, src/client/app/desktop/views/components/note-detail.vue, src/client/app/desktop/views/components/sub-note-content.vue, src/client/app/desktop/views/components/users-list.item.vue, src/client/app/desktop/views/components/window.vue, src/client/app/desktop/views/pages/drive.vue, src/client/app/desktop/views/pages/favorites.vue, src/client/app/desktop/views/pages/home-customize.vue, src/client/app/desktop/views/pages/user-list.users.vue, src/client/app/desktop/views/pages/user/user.timeline.vue, src/client/app/desktop/views/widgets/profile.vue
=> moar and moar i18n

docs/setup.en.md
=> Update build docs

src/client/app/mobile/views/components/post-form.vue
=> fix: validate post's text on mobile client.

src/server/api/endpoints/notes/create.ts
=> fix: when text is null, bug can pass validation.

src/client/assets/manifest.json
/assets/favicon/192.pngは生成すること(ビルドスクリプトでは生成されていないようだったので)
=> Improve web app manifest(#1716)

src/client/assets/manifest.json
=> Replace "size" to "sizes"

src/client/app/common/views/components/note-header.vue
https://misskey.xyz/notes/5b2b5bcc78c9d60baf8c7e3d
=> Improve note-header

src/client/app/desktop/views/components/notes.note.vue, src/client/app/desktop/views/pages/deck/deck.note.vue, src/client/app/desktop/views/pages/user/user.profile.vue, src/client/app/desktop/views/pages/user/user.vue, src/client/app/desktop/views/pages/welcome.vue, src/client/app/mobile/views/components/note.vue
投稿のタグのマージンと色の最適化(標準的な赤にした)
ユーザーページの修正(幅が伸びる、profileの色)
ウェルカムページの修正(ダークモード時)
=> trifling style changes

package.json
=> fix(package): update ts-node to version 7.0.0

package.json
=> fix(package): update webpack to version 4.14.0

package.json
=> fix(package): update hard-source-webpack-plugin to version 0.11.0
